# Generated by Django 3.0.6 on 2020-05-10 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_auto_20200510_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 8, 28, 31, 284235)),
        ),
    ]
