# Generated by Django 3.0.6 on 2020-05-10 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_auto_20200510_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default='alias', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 9, 12, 28, 948368)),
        ),
    ]
